spring.datasource.url=jdbc:postgresql://administrative.cr060gg40asv.eu-central-1.rds.amazonaws.com:5432/administrative
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.formate_sql=true;
spring.jpa.hibernate.naming.strategy=org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



spring.jpa.show-sql=true


#springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.enabled=true

client.origin=http://localhost:3000
server.port=8080

aws.accessKeyId=AKIAQ3EGRB7F5X6ZEDVM
aws.secretKey=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
aws.region=eu-central-1